### ISSUE TITLE
tryhaskell box is timing out on everything

### ISSUE THREAD

**Issue by gbaz** [tryhaskell/tryhaskell#46]
λ test
mueval-core: Time limit exceeded
ExitFailure 1

**Comment by sordina** [comment]
Looks like this really is being caused by a timeout. I increased MUEVAL_TIMEOUT locally and the error disappeared. Still interesting that this timeout started occurring.

**Comment by chrisdone** [comment]
It's a small droplet. mueval isn't cleaning up after itself and leaving /tmp/ghc* directories in /tmp. There are now 300K of them in /tmp. I think this might be affected the timeout. I'm clearing the directory, we'll see if it helps in a minute.

**Comment by chrisdone** [comment]
Looks like that fixed it. But it's still timing out on the bigger computation like doing IO. I'm going to resize the droplet to give it more power.

**Comment by chrisdone** [comment]
OK, adding double RAM and another CPU didn't change anything. I've adjusted the timeout to 3 seconds which helps with the IO examples.
